/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */



/**
 *
 * @author Zé Maria Valentim
 */
public class NewPizzaForm extends javax.swing.JFrame {

    /**
     * Creates new form NewPizzaForm
     */
    private Pizza pizza;
    private OrderForm orderForm;
    
    
    public NewPizzaForm(OrderForm parent) {
        initComponents();
        orderForm =parent;
        pizza = new Pizza();
        for(Size s : Size.values()){
            this.cbbSize.addItem(s.name());
            pizza.setSize(Size.valueOf(cbbSize.getSelectedItem().toString()));
        }
        
        for(Crust c : Crust.values()){
            this.cbbCrust.addItem(c.name());
            pizza.setCrust(Crust.valueOf(cbbCrust.getSelectedItem().toString()));
        }
        
        for(Sauce s : Sauce.values()){
            this.cbbSauce.addItem(s.name());
            pizza.setSauce(Sauce.valueOf(cbbSauce.getSelectedItem().toString()));
        }
        
        for(Topping t : Topping.values()){
            this.cbbTopping1.addItem(t.name());
            pizza.setTopping1(Topping.valueOf(cbbTopping1.getSelectedItem().toString()));
        }
        
         for(Topping t : Topping.values()){
            this.cbbTopping2.addItem(t.name());
            pizza.setTopping2(Topping.valueOf(cbbTopping2.getSelectedItem().toString()));
        }
         this.txtInfoPizza.setText(pizza.pizzaInfo());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbbSize = new javax.swing.JComboBox<>();
        lblSize = new javax.swing.JLabel();
        cbbCrust = new javax.swing.JComboBox<>();
        lblCrust = new javax.swing.JLabel();
        cbbTopping1 = new javax.swing.JComboBox<>();
        lblTopping1 = new javax.swing.JLabel();
        lblTopping2 = new javax.swing.JLabel();
        cbbTopping2 = new javax.swing.JComboBox<>();
        cbbSauce = new javax.swing.JComboBox<>();
        lblSauce = new javax.swing.JLabel();
        btnAddOrder = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtInfoPizza = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        cbbSize.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbbSizeItemStateChanged(evt);
            }
        });

        lblSize.setText("SIZE");

        cbbCrust.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbbCrustItemStateChanged(evt);
            }
        });

        lblCrust.setText("CRUST");

        cbbTopping1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbbTopping1ItemStateChanged(evt);
            }
        });

        lblTopping1.setText("TOPPING 1");

        lblTopping2.setText("TOPPING 2");

        cbbTopping2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbbTopping2ItemStateChanged(evt);
            }
        });

        cbbSauce.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbbSauceItemStateChanged(evt);
            }
        });

        lblSauce.setText("SAUCE");

        btnAddOrder.setText("ADD TO ORDER");
        btnAddOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddOrderActionPerformed(evt);
            }
        });

        btnCancel.setText("CANCEL");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        txtInfoPizza.setEditable(false);
        txtInfoPizza.setColumns(20);
        txtInfoPizza.setRows(5);
        jScrollPane1.setViewportView(txtInfoPizza);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 108, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCrust, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblTopping1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblSize, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblSauce, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblTopping2, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cbbSauce, 0, 139, Short.MAX_VALUE)
                                    .addComponent(cbbTopping2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbbTopping1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbbCrust, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbbSize, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnCancel)
                                .addGap(18, 18, 18)
                                .addComponent(btnAddOrder)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbbSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSize))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbbCrust, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCrust))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbbTopping1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTopping1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTopping2)
                    .addComponent(cbbTopping2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbbSauce, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSauce))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddOrder)
                    .addComponent(btnCancel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnAddOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddOrderActionPerformed
        // TODO add your handling code here:
        this.orderForm.addPizza(pizza);
        this.dispose();
    }//GEN-LAST:event_btnAddOrderActionPerformed

    private void cbbSizeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbbSizeItemStateChanged
        // TODO add your handling code here:
        if(evt.getStateChange() != java.awt.event.ItemEvent.SELECTED ){
            pizza.setSize(Size.valueOf(cbbSize.getSelectedItem().toString()));
            infoPizza(pizza);
        }
       
        
    }//GEN-LAST:event_cbbSizeItemStateChanged

    private void cbbSauceItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbbSauceItemStateChanged
        // TODO add your handling code here:
         if(evt.getStateChange() != java.awt.event.ItemEvent.SELECTED ){
            pizza.setSauce(Sauce.valueOf(cbbSauce.getSelectedItem().toString()));
            infoPizza(pizza);
         }
    }//GEN-LAST:event_cbbSauceItemStateChanged

    private void cbbTopping2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbbTopping2ItemStateChanged
        // TODO add your handling code here:
         if(evt.getStateChange() != java.awt.event.ItemEvent.SELECTED ){
            pizza.setTopping2(Topping.valueOf(cbbTopping2.getSelectedItem().toString()));
            infoPizza(pizza);
         }
    }//GEN-LAST:event_cbbTopping2ItemStateChanged

    private void cbbCrustItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbbCrustItemStateChanged
        // TODO add your handling code here:
        if(evt.getStateChange() != java.awt.event.ItemEvent.SELECTED ){
            pizza.setCrust(Crust.valueOf(cbbCrust.getSelectedItem().toString()));
            infoPizza(pizza);
         }
    }//GEN-LAST:event_cbbCrustItemStateChanged

    private void cbbTopping1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbbTopping1ItemStateChanged
        // TODO add your handling code here:
        if(evt.getStateChange() != java.awt.event.ItemEvent.SELECTED ){
            pizza.setTopping1(Topping.valueOf(cbbTopping1.getSelectedItem().toString()));
            infoPizza(pizza);
         }
    }//GEN-LAST:event_cbbTopping1ItemStateChanged

    private void infoPizza(Pizza pizza){
        this.txtInfoPizza.setText(pizza.pizzaInfo());
    }
    
    
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(NewPizzaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(NewPizzaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(NewPizzaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(NewPizzaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new NewPizzaForm().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddOrder;
    private javax.swing.JButton btnCancel;
    private javax.swing.JComboBox<String> cbbCrust;
    private javax.swing.JComboBox<String> cbbSauce;
    private javax.swing.JComboBox<String> cbbSize;
    private javax.swing.JComboBox<String> cbbTopping1;
    private javax.swing.JComboBox<String> cbbTopping2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCrust;
    private javax.swing.JLabel lblSauce;
    private javax.swing.JLabel lblSize;
    private javax.swing.JLabel lblTopping1;
    private javax.swing.JLabel lblTopping2;
    private javax.swing.JTextArea txtInfoPizza;
    // End of variables declaration//GEN-END:variables
}
